import { expect, test } from '@playwright/test'

test('profile actions preserve personality drafts and expose state', async ({ page }) => {
  await page.goto('/tests/fixture.html')
  await page.getByRole('button', { name: 'AI', exact: true }).click()

  const personality = page.locator('.personality-editor')
  const profile = page.locator('.profile-instructions-editor')
  const protectedInstructions = page.locator('.protected-instructions-card')
  await expect(profile.locator('textarea')).toHaveValue('')
  await expect(protectedInstructions).not.toHaveAttribute('open', '')
  await expect(personality.getByText('Built-in', { exact: true })).toBeVisible()
  await expect(personality.getByText('Active', { exact: true })).toBeVisible()

  await personality.locator('textarea').fill('personality draft')
  await profile.locator('textarea').fill('profile draft')
  await personality.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(profile.locator('textarea')).toHaveValue('profile draft')

  await personality.locator('textarea').fill('another personality draft')
  await profile.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(personality.locator('textarea')).toHaveValue('another personality draft')
  await expect(profile.getByText('Runtime only', { exact: true })).toBeVisible()

  await profile.locator('textarea').fill('saved profile draft')
  await personality.locator('textarea').fill('saved personality draft')
  await personality.getByRole('button', { name: 'Save', exact: true }).click()
  await profile.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(profile.locator('textarea')).toHaveValue('saved profile draft')
  await expect(personality.locator('textarea')).toHaveValue('saved personality draft')
  await expect(profile.getByText('Saved', { exact: true })).toBeVisible()

  page.once('dialog', (dialog) => { void dialog.accept() })
  await profile.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(profile.locator('textarea')).toHaveValue('')
  await expect(personality.locator('textarea')).toHaveValue('saved personality draft')

  await protectedInstructions.locator('summary').click()
  await expect(protectedInstructions.locator('textarea')).toHaveValue('Synthetic shared instructions.')
  await expect(protectedInstructions.locator('textarea')).toHaveAttribute('readonly', '')
})

test('custom personality CRUD keeps save and activation separate', async ({ page }) => {
  await page.goto('/tests/fixture.html')
  await page.getByRole('button', { name: 'AI', exact: true }).click()
  const personality = page.locator('.personality-editor')

  await personality.getByRole('button', { name: 'New personality', exact: true }).click()
  const createForm = personality.locator('.personality-inline-form')
  await createForm.getByLabel('Name').fill('  Focused helper  ')
  await createForm.getByLabel('Prompt').fill('exact custom prompt\nwith a second line')
  await createForm.getByRole('button', { name: 'Create', exact: true }).click()

  await expect(personality.locator('select')).toHaveValue('Focused helper')
  await expect(personality.getByText('Custom', { exact: true })).toBeVisible()
  await expect(personality.getByText('Active', { exact: true })).toBeHidden()
  await expect(personality.locator('textarea')).toHaveValue('exact custom prompt\nwith a second line')

  await personality.locator('textarea').fill('saved custom prompt')
  await personality.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(personality.locator('textarea')).toHaveValue('saved custom prompt')
  await expect(personality.getByText('Active', { exact: true })).toBeHidden()

  await personality.locator('textarea').fill('activation must keep this draft')
  await personality.getByRole('button', { name: 'Set active', exact: true }).click()
  await expect(personality.getByText('Active', { exact: true })).toBeVisible()
  await expect(personality.locator('textarea')).toHaveValue('activation must keep this draft')
  const savedPrompts = await page.evaluate(() => window.pywebview!.api.get_personalities())
  expect(savedPrompts.personalities.find((item) => item.name === 'Focused helper')?.prompt).toBe('saved custom prompt')

  await personality.locator('textarea').fill('unsaved draft survives rename')
  await personality.getByRole('button', { name: 'Rename', exact: true }).first().click()
  const renameForm = personality.locator('.personality-rename-form')
  await renameForm.getByLabel('New name').fill('Renamed helper')
  await renameForm.getByRole('button', { name: 'Rename', exact: true }).click()
  await expect(personality.locator('select')).toHaveValue('Renamed helper')
  await expect(personality.locator('textarea')).toHaveValue('unsaved draft survives rename')
  await expect(personality.locator('select option[value="Focused helper"]')).toHaveCount(0)
  await expect(personality.getByText('Active', { exact: true })).toBeVisible()

  page.once('dialog', (dialog) => { void dialog.dismiss() })
  await personality.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(personality.locator('select')).toHaveValue('Renamed helper')
  page.once('dialog', (dialog) => { void dialog.accept() })
  await personality.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(personality.locator('select')).toHaveValue('neutral')
  await expect(personality.getByText('Custom', { exact: true })).toBeHidden()
  const calls = await page.evaluate(() => (window as unknown as { aiCalls: unknown[][] }).aiCalls)
  expect(calls.map((call) => call[0])).toEqual(expect.arrayContaining([
    'create_personality', 'save_personality', 'set_active_personality', 'rename_personality', 'delete_personality',
  ]))
})

test('built-in controls restrict custom-only actions and reset', async ({ page }) => {
  await page.goto('/tests/fixture.html')
  await page.getByRole('button', { name: 'AI', exact: true }).click()
  const personality = page.locator('.personality-editor')

  await expect(personality.getByRole('button', { name: 'Rename', exact: true }).first()).toBeDisabled()
  await expect(personality.getByRole('button', { name: 'Delete', exact: true })).toBeDisabled()
  await expect(personality.getByRole('button', { name: 'Set active', exact: true })).toBeDisabled()
  await expect(personality.getByRole('button', { name: 'Reset', exact: true })).toBeDisabled()

  await personality.getByRole('button', { name: 'New personality', exact: true }).click()
  const createForm = personality.locator('.personality-inline-form')
  await createForm.getByLabel('Name').fill('Custom one')
  await createForm.getByLabel('Prompt').fill('Prompt')
  await createForm.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(personality.getByRole('button', { name: 'Reset', exact: true })).toBeDisabled()
  await expect(personality.getByRole('button', { name: 'Delete', exact: true })).toBeEnabled()
})

test('personality save errors retain the unsaved draft', async ({ page }) => {
  await page.goto('/tests/fixture.html?savePersonalityError')
  await page.getByRole('button', { name: 'AI', exact: true }).click()
  const personality = page.locator('.personality-editor')
  await personality.locator('textarea').fill('keep this personality draft')
  await personality.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(personality.locator('textarea')).toHaveValue('keep this personality draft')
  await expect(page.getByRole('alert').locator('span')).toHaveText('Personality could not be saved.')
})

test('failed creation retains name and prompt and validates blank names', async ({ page }) => {
  await page.goto('/tests/fixture.html?createPersonalityError')
  await page.getByRole('button', { name: 'AI', exact: true }).click()
  const personality = page.locator('.personality-editor')
  await personality.getByLabel('Editable prompt').fill('Keep the existing personality draft')
  await personality.getByRole('button', { name: 'New personality', exact: true }).click()
  const form = personality.locator('.personality-inline-form')
  await expect(personality.getByRole('button', { name: 'Save', exact: true })).toHaveCount(0)
  await form.getByLabel('Name').fill('   ')
  await form.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('1–64 characters')
  await form.getByLabel('Name').fill('Keep name')
  await form.getByLabel('Prompt').fill('Keep prompt')
  await form.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Personality could not be created.')
  await expect(form.getByLabel('Name')).toHaveValue('Keep name')
  await expect(form.getByLabel('Prompt')).toHaveValue('Keep prompt')
  await expect(personality.locator('select')).toHaveValue('neutral')
  await personality.getByRole('button', { name: 'Cancel new personality', exact: true }).click()
  await expect(personality.getByLabel('Editable prompt')).toHaveValue('Keep the existing personality draft')
})

test('failed rename and delete retain the collection and drafts', async ({ page }) => {
  await page.goto('/tests/fixture.html?renamePersonalityError&deletePersonalityError')
  await page.getByRole('button', { name: 'AI', exact: true }).click()
  const personality = page.locator('.personality-editor')
  await personality.getByRole('button', { name: 'New personality', exact: true }).click()
  const createForm = personality.locator('.personality-inline-form')
  await createForm.getByLabel('Name').fill('Keep personality')
  await createForm.getByRole('button', { name: 'Create', exact: true }).click()
  await personality.locator('textarea').fill('Keep draft')
  await personality.getByRole('button', { name: 'Rename', exact: true }).click()
  const renameForm = personality.locator('.personality-rename-form')
  await renameForm.getByLabel('New name').fill('Keep rename draft')
  await renameForm.getByRole('button', { name: 'Rename', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Personality could not be renamed.')
  await expect(renameForm.getByLabel('New name')).toHaveValue('Keep rename draft')
  await expect(personality.locator('select')).toHaveValue('Keep personality')
  await expect(personality.getByLabel('Editable prompt')).toHaveValue('Keep draft')
  page.once('dialog', (dialog) => { void dialog.accept() })
  await personality.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Personality could not be deleted.')
  await expect(personality.locator('select')).toHaveValue('Keep personality')
  await expect(personality.getByLabel('Editable prompt')).toHaveValue('Keep draft')
})

test('failed profile action retains its draft', async ({ page }) => {
  await page.goto('/tests/fixture.html?profileError')
  await page.getByRole('button', { name: 'AI', exact: true }).click()

  const profile = page.locator('.profile-instructions-editor')
  await profile.locator('textarea').fill('keep this after failure')
  await profile.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(profile.locator('textarea')).toHaveValue('keep this after failure')
  await expect(page.getByRole('alert').locator('span')).toHaveText('Profile instructions could not be updated.')
})
